name = "golang"
title = "Go"
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/usage-examples"
]

intersphinx = [
  "https://www.mongodb.com/docs/manual/objects.inv",
  "https://www.mongodb.com/docs/drivers/objects.inv",
  "https://www.mongodb.com/docs/atlas/objects.inv"
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-long = "MongoDB Go Driver"
docs-branch = "master" # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
version = "v1.10.0-beta1" # always set this to the driver branch (i.e. v1.7.0, v1.8.0, etc.)
example = "https://raw.githubusercontent.com/mongodb/docs-golang/{+docs-branch+}/source/includes/usage-examples/code-snippets"
api = "https://pkg.go.dev/go.mongodb.org/mongo-driver@{+version+}"
