name = "golang"
title = "Go"
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/usage-examples"
]

intersphinx = [
  "https://docs.mongodb.com/manual/objects.inv",
  "https://docs.atlas.mongodb.com/objects.inv",
]

[constants]
docs-branch = "master" # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
version = "v1.7.2" # always set this to the driver branch (i.e. v1.7.0, v1.8.0, etc.)
example = "https://raw.githubusercontent.com/mongodb/docs-golang/{+docs-branch+}/source/includes/usage-examples/code-snippets"
api = "https://pkg.go.dev/go.mongodb.org/mongo-driver@{+version+}"
