name = "golang"
title = "Go"
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/usage-examples"
]

intersphinx = [
  "https://docs.mongodb.com/manual/objects.inv",
  "https://docs.atlas.mongodb.com/objects.inv",
  "https://docs.python.org/2/python2.inv"
]

[constants]
docs-branch = "master" # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
driver-branch = "v1.7.0" # always set this to the driver branch (i.e. 1.7.0, 1.8.0, etc.)
raw-github = "https://raw.githubusercontent.com/mongodb/docs-golang/{+docs-branch+}/source/includes"
example = "{+raw-github+}/usage-examples/code-snippets"
godocs = "https://pkg.go.dev/go.mongodb.org/mongo-driver@{+driver-branch+}"
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"
