name = "golang"
title = "Go"
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/builders"
]

[constants]
docs-branch = "master" # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
driver-branch = "1.7.0" # always set this to the driver branch (i.e. 1.7.0, 1.8.0, etc.)
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"
