name = "golang"
title = "Go"
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/builders"
]

[constants]
branch = "master"
version = 4.0
package-name-org = "mongodb-org"
pgp-version = "{+version+}"
